// Login Admin
POST http://localhost:5001/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###
// Login User
POST http://localhost:5001/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "user"
}

###
// Logout
DELETE http://localhost:5001/logout

###
// Me
GET http://localhost:5001/me