// Create a Product
POST http://localhost:5001/product
Content-Type: application/json

{
    "name": "",
    "price": ""
}

###
// Get All Product
GET http://localhost:5001/product

###
// Get Singel Product
GET http://localhost:5001/product/uuid

###
// Update a Product
PATCH http://localhost:5001/product/uuid
Content-Type: application/json

{
    "name": "",
    "price": ""
}

###
// Delete a Product
DELETE http://localhost:5001/product/uuid